//
//  InsighterKit.swift
//  insighter-app
//
//  Created by Jan Dammshäuser on 16.08.16.
//  Copyright (c) 2016 insighter. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

import UIKit

open class InsighterKit: NSObject {

	/// / Drawing Methods

	open class func drawSliderView(sliderColor: UIColor = UIColor(red: 1.000, green: 0.651, blue: 0.263, alpha: 1.000), width: CGFloat = 311, sliderFraction: CGFloat = 0.5) {
		/// / General Declarations
		let context = UIGraphicsGetCurrentContext()

		/// / Color Declarations
		let backgroundColor = UIColor(red: 0.878, green: 0.878, blue: 0.878, alpha: 1.000)

		/// / Variable Declarations
		let scaling: CGFloat = width / 311.0
		let height: CGFloat = scaling * 75
		let topMargin: CGFloat = (85 - height) / 2.0
		let angle: CGFloat = -45 - sliderFraction * (135 - 45)

		/// / SliderGroup
		context?.saveGState()
		context?.translateBy(x: 0, y: topMargin)
		context?.scaleBy(x: scaling, y: scaling)

		context?.beginTransparencyLayer(auxiliaryInfo: nil)

		/// / Clip Clip
		let clipPath = UIBezierPath()
		clipPath.move(to: CGPoint(x: 295.31, y: 73.64))
		clipPath.addLine(to: CGPoint(x: 311, y: 57.81))
		clipPath.addCurve(to: CGPoint(x: 155.93, y: 0), controlPoint1: CGPoint(x: 275.69, y: 22.72), controlPoint2: CGPoint(x: 219.38, y: 0))
		clipPath.addCurve(to: CGPoint(x: 0, y: 58.68), controlPoint1: CGPoint(x: 91.97, y: 0), controlPoint2: CGPoint(x: 35.25, y: 23.09))
		clipPath.addLine(to: CGPoint(x: 16.18, y: 75))
		clipPath.addCurve(to: CGPoint(x: 156.43, y: 23.34), controlPoint1: CGPoint(x: 47.15, y: 43.76), controlPoint2: CGPoint(x: 98.42, y: 23.34))
		clipPath.addCurve(to: CGPoint(x: 295.31, y: 73.64), controlPoint1: CGPoint(x: 213.59, y: 23.34), controlPoint2: CGPoint(x: 264.21, y: 43.17))
		clipPath.close()
		clipPath.usesEvenOddFillRule = true

		clipPath.addClip()

		/// / BackgroundRect Drawing
		let backgroundRectPath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 311, height: 75))
		backgroundColor.setFill()
		backgroundRectPath.fill()

		/// / AngledRect Drawing
		context?.saveGState()
		context?.translateBy(x: 155.03, y: 214.97)
		context?.rotate(by: -angle * CGFloat(M_PI) / 180)

		let angledRectPath = UIBezierPath(rect: CGRect(x: -229.11, y: 0, width: 458.21, height: 246.12))
		sliderColor.setFill()
		angledRectPath.fill()

		context?.restoreGState()

		context?.endTransparencyLayer()

		context?.restoreGState()
	}

	open class func drawCanvas1(sliderColor: UIColor = UIColor(red: 1.000, green: 0.651, blue: 0.263, alpha: 1.000)) {
		/// / General Declarations
		let context = UIGraphicsGetCurrentContext()

		/// / Symbol Drawing
		let symbolRect = CGRect(x: 72, y: 83, width: 311, height: 75)
		context?.saveGState()
		UIRectClip(symbolRect)
		context?.translateBy(x: symbolRect.origin.x, y: symbolRect.origin.y)
		context?.scaleBy(x: symbolRect.size.width / 311, y: symbolRect.size.height / 85)

		InsighterKit.drawSliderView(sliderColor: sliderColor, width: 311, sliderFraction: 0.5)
		context?.restoreGState()
	}
}
